project:
  type: website

website:
  title: "Dad Book Club"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer:
    center:
      - text: "Subscribe to Dad Book Club"
        href: "https://buttondown.com/jknapp"  # Replace with your Buttondown URL
  feed:
    path: feed.xml

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

