project:
  type: website

website:
  title: "Dad Book Club"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer:
    center:
      - text: "Subscribe to Dad Book Club"
        href: "https://buttondown.com/jknapp"
  site-url: https://dadbook.club

format:
  html:
    theme:
      - cosmo
    css: styles.css

editor: visual
