project:
  type: website

website:
  title: "Dad Book Club"
  site-url: https://dadbook.club
  description: "A dad writes about books."
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
  margin-header: subscribe.html
  page-footer:
    center:
      - text: "Subscribe to Dad Book Club"
        href: "https://buttondown.com/jknapp"

format:
  html:
    theme:
      - minty
    css: styles.css

editor: visual
