---
title: "How Parents From Around the World Can Teach Us To Trust the Process"
subtitle: "Playing the long game, making fewer demands, and fostering caring relationships can create harmonious households -- even if things don't always work out in the meantime."
date: 2026-05-31
categories: [parenting]
page-layout: full
title-block-banner: true
---

## The World That Might Be

My alarm wakes me up in the morning, and I open the door to my daughters' room and say "Good morning." They stir, rub their eyes, and manage a sleepy "Good morning." I feed the dog and finish getting myself ready. As I walk back to the kitchen, the 6 year old is putting on her shoes and the 9 year old is dressed and putting away a couple books out from the night before. I walk to the kitchen, pop some slices of bread into the toaster, and pull out some boiled eggs. We listen to music while we eat. Our mornings are calm, quiet, and orderly. Our evenings are similar: we eat together when we can, share our stories from our day and pressing thoughts, and break for bed when tired. No tantrums, no shouting, no deals, and no tears. The kids behave better, too.

I believe in this vision of familial peace. Alas, our home has yet to arrive. As I type, our two daughters are shouting at each other about socks for some reason. But this world without shouting has never seemed more real than since I read *Hunt, Gather, Parent: What Ancient Cultures Can Teach Us About the Lost Art of Raising Happy, Helpful Little Humans* by Michaeleen Doucleff. She says "Togetherness is easy. It's relaxing. It flows. It's what happens when we all stop trying to control each other's actions and simply let each other be." I want that for us.

## *Hunt, Gather, Parent*

The book is different from many parenting books in several refreshing ways. The author, a science reporter for NPR, is not a parenting expert and generously models learning the books' many lessons. She includes the knowledge and wisdom from many experts including real life parents who have managed to avoid the modern, western, style of parenting. Doucleff describes her time living with these parents with her own daughter, and shares their strategies around parenting.

The bulk of the book focuses on Doucleff's travels learning from parents in three cultures. From the Maya families, Doucleff shares the practice of allowing even the youngest children to help in their own way. The logic is that 3 year-olds who make a mess squishing dough slowly become 10 year-olds who can help cook a meal. When Doucleff travels above the Arctic Circle, she meets Inuit parents who never get angry with their children. In Tanzania, Hadzabe families show how capable young people can be when they are given responsibility and autonomy. These glimpses into other cultures is fascinating in and of themselves, but the example of these families is truly inspiring. The stories of these families helped me to connect some dots and since reading the book, I have tried to integrate a several ideas into my own life.

## The Long Game

The parent role-models in *Hunt, Gather, Parent* are not in a hurry. They know that kids need a lot of time and support while learning new skills. They know that doing anything with a toddler will take longer and be harder than just doing it themselves. But the only way for them to get better is to let them try. Kids – especially toddlers – want to help, and these parents take advantage of that enthusiasm to include them in the learning process. Toddlers are also excellent learners because they are patient with themselves and don't mind making mistakes or looking bad. Older kids and adults can get embarrassed when they are making mistakes.

Doucleff shows that including kids in household task not only allows them to become capable, but they learn to be helpful as well. This isn't a trick to get kids to do things – or to "listen". This is bringing them into the family and making the work of the family and the household meaningful to them. When we include kids in the household tasks, they will learn that they have a role in the family. When we tell kids to help by getting out of the way or going to play by themselves, they learn that playing with toys or watching TV is their role in the family, and they might be surprised when their parent eventually wants them to do things.

The kids Doucleff meets understand that they are part of the family and the family has shared goals. Doucleff highlights that the Maya kids do things like the dishes without being told, or encourage their parent to clean a room together. Their word for this responsibility is *acomedido.* The Hadzabe families are explicitly oppossed to bossing kids around and will call out other parents who are being too demanding of their kids. The kids in these families do not need the bossing. They will wake up on their own to tend to chickens before getting themselves and younger siblings to school.

This is not an instant process and Doucleff is more forthright in this regard than other writers of parenting books. The kids -- and we the parents -- will face the consequences when they make mistakes. The kitchen will get messy, chores will not be done, we'll be late for things, and sometimes the kids might even get a little hurt. This is all part of the process of learning cause and effect and what responsibility actually means. It also teaches the kids to be resiliant when things don't work out.

And learning emotional intelligence, like learning how to cook, clean, or take care of chickens takes time. Teaching emotional intelligence takes patience and intention. The Inuit are the most impressive example of this. Doucleff tells a story about parenting in public when first arriving in the Artic circle while her young daughter has a meltdown. Doucleff's response is extremely relatable, but anathema to the Inuit parents who calmly step in and give Doucleff and her daughter a much needed break from each other. The Inuit parents face tantrums with perfect equanimity knowing that calmness will win out in the long run. Doucleff writes "Inuit view yelling at a small child as demeaning, elders tell me. The adult is basically stooping to the level of the child—or throwing a grown-up version of a tantrum. Same goes for scolding or talking to children in an angry voice. 'Getting angry at a child has no purpose,' says eighty-three-year-old Martha Tikivik. Born in an igloo on Baffin Island, she has raised six children. 'Getting angry isn’t going to solve your problem. It only stops communication between the child and the mom.'" This is one of several examples where Doucleff reminds us that kids learn first from what we model. If we model shouting and making demands, we can expect the same from our children. The other thing to note in that quote is the attention to the relationship between the child and parent and the importance of maintaining communication.

## Relationships With Your Children

The answer on how to co-exist with your children and get them to help around the house is not straight forward, but the one of the most important parts is to care about your relationship with your children *and* to help them care about it too. Relationships are often invisible to us in the west. The US is a very individualized culture where we often think about relationships transactionally if at all. We talk about filling and emptying cups the way we might deposit and withdraw money from a bank. The implication being that if we make someone happy -- fill their cup -- we can later cash in and empty the cup by asking them for something. It's wild that we have this model for young children, and I'm as guilty as anyone here. I've said things like "I was just pushing you on the swing for 20 minutes; can't you get ready for bed when I ask you to?" Not only does it not work, but it cheapens the time I got to spend pushing her on the swing. Making demands and expecting compliance based on my authority as a parent, or trying to cash in on previous time spent with them all weaken my relationship with them. These actions make it less likely they will want to support me and the things I care about.

The books highlights the relationships parents have with their children and that children have with their families. Doucleff reminds us that autonomy is not the same as independence. "\[T\]he two concepts have different meanings, and this difference is essential to understanding how hunter-gatherer parents raise such self-reliant and kind children. It’s also key to understanding a way of parenting that does not involve control -- a way of collaborating with your child that smoothes your relationship and helps your child feel less anxious. The difference has to do with connectivity. Independence means not needing or not being influenced by others. An independent child operates like a solitary planet. They’re disconnected. They have no obligations to their family or their community around them. And in return, the family and community have no expectations of the child." Having high expectations of our family members while patiently supporting them to meet those expectations is an example of both love and leadership. We don't often encounter these two idea together they but succictly capture a big idea for what I hope to accomplish as a parent.

The book helped to make parenting while strengthening my relationships with my children feel possible, but it's not the first place I've encountered this idea. *Non-Violent Communication* by Marshall Rosenberg emphasizes communicating in ways that strengthen our relationships. He suggests that making demands of anyone is a recipe for disappointment or resentment. Rosenberg advises us to make requests of others and explain how the realization of the request will satisfy our needs and strengthen our relationship. This is a beautiful sentiment that I think about nearly every day, but I struggle applying this to my own children and while still getting them to school on time.

*The Gardener and The Carpenter* by Alison Gopnik is another book with sage advice about tending to your childrens' environment as a gardener would and watching them bloom as they will. This is opposed to a carpenter who may come in with blueprints and hammers and attempt to force his will upon children under the illusion that they will conform to the blueprint – I picture Homer Simpson building "le grille". This is very high-level advice and useful for making big plans, but it does not speak to the every day tasks and power-struggles of parenting. Gopnik advocates for allo-parenting -- something Doucleff discusses in *Hunt, Gather, Parent*, but again as a general strategy not as a daily tactic.

Our pediatrician loves *How to Talk So Kids Will Listen & Listen So Kids Will Talk* by Adele Faber and Elaine Mazlish. I read the "little kids" version and it was probably my favorite book on the day-to-day tasks of parenting before I read *Hunt, Gather, Parent*. It does a great job of explaining the concepts, giving examples, highlighting big ideas, and even includes comics demonstrating the concepts. It wasn't as fun to read as *Hunt, Gather, Parent* though, and while the authors caution us to not boss our kids around, the alternative didn't fully click with me until *Hunt, Gather, Parent*.

Ultimately, I learned something from each of these books -- and others -- and it might be that I read them in the right order for *Hunt, Gather, Parent* to come in and connect all of these big ideas. I especially thought about *Non-violent Communication* a lot while reading *Hunt, Gather, Parent* and I frequently saw real examples of NVC techniques that were previously hard to imagine. I often said to myself, "so that's how you do that" while seeing NVC in the actions the parents from other cultures did intuitively.

## My Progress and A Request

I finished *Hunt, Gather, Parent* about 4 months ago. I've since skimmed through *Non-violent Communication* as a refresher and tried to more explicitly connect these ideas. I've really focused on the autonomy piece and stress to my kids that they are responsible for their own decisions. I've tried to raise my expectations for them. Sometimes it has worked and other times it hasn't. Throughout this process, my two kids have reminded me how different they are. One takes very well to autonomy, and the other seems to value a bit more scaffolding and support. I'm working on that balance and differentiating for each kid and for different moments, but I am short on other tools and catch myself resorting to demands pretty quickly. I appreciated Doucleff's transparency that even in the most peacful households raising kids is not always pretty and certainly not easy. We need to allow kids to experience the consequences of their decisions -- within reason -- but we all have our own thresholds for choas and risk. Including kids while cooking has been an easier one for me -- it's just a messy counter -- but my good intentions go out the window when we are about to be late for something. I have not yet figured out how to motivate them to get ready faster. Being late is meaningless to children too young to tell time. My solution has been to wake up earlier and earlier, but it's getting a little out of hand. Especially as the children have thrown a small mutinty against bedtimes. Their revolt caught me in a generous spirit however as in a later chapter, Doucleff suggests that bedtimes might not be as important as we all thought. Our results have been mixed thus far, but the experiment continues.

I've recommended this book to just about every parent I know, but I think if you made it this far you know if book is for you. I'll save my request for something else that I have noticed since reading the book that Doucleff does not talk about. My request is that we communicate more compassion for parents who are giving it a go. Western parents embarass easily. We do not want our kids to struggle in public and we really hate to be seen with unruly kids. This is part of the process, and even the best parents will struggle with the strategies Doucleff suggests (or any other strategies) and we all get to see other children learn in public. We can give these parents a smile, a nod, or a word of encouragment. "She'll figure it out" or "he'll get there" could go a long way to show parents that we know their kid is learning, it's OK, and that even in public, they can trust the process.